apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgbot
  template:
    metadata:
      labels:
        app: tgbot
    spec:
      containers:
        - name: bot
          image: myink/meowbot-tg:latest
          env:
            - name: TELEGRAM_BOT_TOKEN
              value: "7194611685:AAHSZKXXYoiG1pZ0EaVpRHKQVO1E3ectByU"
            - name: MONGO_DB_HOST
              value: "db.mongo"
            - name: TELEGRAM_API_URL
              value: "https://telegram-bot-api"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tgbot
spec:
  selector:
    app: tgbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
