apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db.mongo
  template:
    metadata:
      labels:
        app: db.mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  selector:
    app: db.mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
