name: GoUnit

on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.1'
      - name: Tests with coverage
        run: go test github.com/nikmy/meowbot -coverprofile="auto_out.cov"
